### ISSUE TITLE
tabs issue in vars.yml

### ISSUE THREAD

**Issue by oren** [chhantyal/5minutes#2]
I got errors when I tried running the ansible-playbook command:

```
ERROR: Syntax Error while loading YAML script, /home/oren/p/5minutes/vars.yml
Note: The error may actually appear before this position: line 9, column 1

user_public_keys:
        - ~/.ssh/id_rsa.pub
^
```

I had to remove the spaces in line 9 and put tab instead. I had to do that for more lines in that file.
Maybe it's because my laptop is Ubuntu?

**Comment by chhantyal** [comment]
Oh it's tabs vs spaces again ;)

My editor uses spaces as default, so you need to adjust your machine.

**Comment by oren** [comment]
got it. thanks
